### ISSUE TITLE
number of queries judged

### ISSUE THREAD

**Issue by yuhongqian** [grill-lab/DL-Hard#1]
Thanks for your good work! 

I counted the number of queries judged in `./dataset/dl_hard-passage.qrels`, and it seems that there are 48 queries instead of 50. In particular, queries 1056416 and 1103153 are not there. Am I missing anything?

**Comment by iain-mackie** [comment]
Thanks @yuhongqian - great catch!

It turns out that those 2 queries (1056416 & 1103153) we judged only for documents during TREC DL 2020 and not passages. This was missed when we created the DL-HARD additional judgments. 

We've had our annotators create new judgements for both queries - qrels, judgments, and baseline evals have all been updated!

Any other thoughts / comments welcome! Cheers.
